name: khafil_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  google_fonts: ^6.1.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
